config/routes.rb
Rails.application.routes.draw do
  root 'cities#index'

  resources :cities do
    resources :restaurants
  end
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :restaurants, dependent: :destroy

	validates_presence_of :name

	def self.by_name
		order(:name)
	end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	RATINGS = [1,2,3,4,5]
	belongs_to :city

	validates_presence_of :name, :food_type
	validates :cost_rating, inclusion: {in: RATINGS}
	validates :open, :alcohol, :take_out, inclusion: {in:[true, false]}

	# class method on active record model is called a scope
	# Restaurant.all.by_name
	def self.by_name
		order(:name)
	end

	def self.ratings
		RATINGS
	end
	# Restaurant.all.by_cost
	def self.by_cost
		order(:cost_rating)
	end

	# Instance Method
	# Restaurant.first.status
	def status
		if self.open
			"The Restaurant: #{self.name} is open for business!"
		else
			"The Restaurant: #{self.name} opens very soon!"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_action :city, except: [:index, :new, :create]
  def index
  	@cities = City.all.by_name
  end

  def show
  end

  def new
  	@city = City.new
  end

  def create
  	@city = City.new(city_params)
  	if @city.save
  		flash[:success] = "City with name: #{@city.name} created!"
  		redirect_to city_path(@city)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @city.update(city_params)
  		flash[:success] = "City with name: #{@city.name} updated!"
  		redirect_to city_path(@city)
  	else
  		render :edit
  	end
  end

  def destroy
  	city_name = @city.name
  	@city.destroy
  	flash[:success] = "City with name: #{city_name} destroyed!"
  	redirect_to cities_path
  end

  private

  	def city_params
  		params.require(:city).permit(:name, :year_est, :population)
  	end

  	def city
  		@city = City.find(params[:id])
  	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :city
  before_action :restaurant, only: [:show, :edit, :update, :destroy]

  def index
  	@restaurants = @city.restaurants
  end

  def show
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
  	@restaurant = @city.restaurants.new(restaurant_params)
  	if @restaurant.save
  		flash[:success] = "Restaurant with name: #{@restaurant.name} created!"
  		redirect_to city_restaurant_path(@city, @restaurant)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @restaurant.update(restaurant_params)
  		flash[:success] = "Restaurant with name: #{@restaurant.name} updated!"
  		redirect_to city_restaurant_path(@city, @restaurant)
  	else
  		render :edit
  	end
  end

  def destroy
  	name = @restaurant.name
  	@restaurant.destroy
  	flash[:success] = "Restaurant with name: #{name} destroyed!"
    redirect_to city_restaurant_path(@city)
  end

  private
  	def restaurant_params
  		params.require(:restaurant).permit(:name, :food_type,
  			:cost_rating, :open, :take_out, :alcohol)
  	end

  	def restaurant
  		@restaurant = @city.restaurants.find(params[:id])
  	end

  	def city
  		@city = City.find(params[:city_id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/cities/_form.html.erb
<% if @city.errors.any? %>
	<div class= 'red-text'>
		<h3>Errors:</h3>
		<ul >
			<%@city.errors.full_messages.each do |message| %>
				<li>
					<%= message %>
				</li>
			<% end%>
		</ul>
	</div>
<% end %>

<%= form_for @city do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :year_est, 'Year EST' %>
	<%= f.select :year_est, (Time.zone.now.year - 100)..(Time.zone.now.year + 1) %>

	<%= f.label :population %>
	<%= f.number_field :population %>

	<%= f.submit %>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City: <%= @city.name %></h1>
<hr />

<%= render(partial: 'form')%>

app/views/cities/index.html.erb
<h1>Cities</h1>
<hr />

<% if @cities.any? %>
	<ul>
		<% @cities.each do |city|%>
			<li>
				<%= link_to city.name, city_path(city) %>
			</li>
		<% end %>
	</ul>
<% else %>
	<h3>No cities, please create one!</h3>
<% end %>

<hr />

<%= link_to "New City", new_city_path %>

app/views/cities/new.html.erb
<h1>Create a city</h1>
<hr />

<%= render(partial: 'form') %>

app/views/cities/show.html.erb
<h1><%= @city.name %></h1>
<hr/ >

<p>Year established: <%= @city.year_est %> </p>
<p>Poplulation: <%= @city.population %></p>
<%= link_to 'Restaurants', city_restaurants_path(@city) %>

<hr/ >

<%= link_to 'Edit', edit_city_path(@city) %>
<%= link_to 'Delete', city_path(@city), method: :delete, data: {confirm: 'Really delete?'} %>
<%= link_to 'All Cities', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CityEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if flash.any? %>
	<% flash.each do |key, value| %>
	<div class="flash <%= key %>">
		<%= value %>
	</div>
	<% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for [@city, @restaurant] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :food_type %>
	<%= f.text_field :food_type %>

	<%= f.label :cost_rating %>
	<%= f.select :cost_rating, Restaurant.ratings %>

	<%= f.label :open %>
	<%= f.select :open, [true, false] %>

	<%= f.label :take_out %>
	<%= f.select :take_out, [true, false] %>

	<%= f.label :alcohol %>
	<%= f.select :alcohol, [true, false] %>

	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant <%= @restaurant.name %></h1>
<hr />

<%= render(partial: 'form')%>

app/views/restaurants/index.html.erb
<h1>
  <%= @city.name %> Restaurants
</h1>
<hr />

<% if @restaurants.any? %>
  <ul>
    <% @restaurants.each do |restaurant| %>
      <li>
        <%= link_to restaurant.name, city_restaurant_path(@city, restaurant) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <h3>No restaurants, please add one!</h3>
<% end %>

<hr />

<%= link_to 'New Restaurants', new_city_restaurant_path(@city) %>
<%= link_to 'Back', city_path(@city) %>

app/views/restaurants/new.html.erb
<h1>New Restaurant In <%= @city.name%> </h1>
<hr />

<%= render(partial: 'form')%>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.status %></h3>
<hr />

<span>Food Type:</span>
<span> <%= @restaurant.food_type %> </span>

<span>Cost Rating:</span>
<span> <%= @restaurant.cost_rating %> </span>

<span>Open:</span>
<span> <%= @restaurant.open %> </span>

<span>Take Out:</span>
<span> <%= @restaurant.take_out %> </span>

<span>Alcohol:</span>
<span> <%= @restaurant.alcohol %> </span>

<hr />

<%= link_to 'Edit', edit_city_restaurant_path(@city, @restaurant) %>

<%= link_to 'Delete', city_restaurant_path(@city, @restaurant), method: :delete, data: {confirm: 'Really delete?'} %>

<%= link_to "#{@city.name} restaurants", city_restaurants_path(@city) %>